"""AI-powered test case enhancer using Google Gemini.

Takes the basic test cases generated by the regex-based pipeline and
enhances them with detailed, app-specific steps by sending code context
to Gemini.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass

logger = logging.getLogger(__name__)


def enhance_test_cases_with_ai(
    test_cases: list,
    file_changes: list,
    locators: list,
    patterns: list,
    metadata,
    change_summary: str = "",
) -> list:
    """Enhance test case steps using Gemini AI.

    Sends code context and change summary to Gemini and asks it to generate
    detailed, automation-ready steps (e.g., "Login as user", "Tap hamburger menu",
    "Navigate to Transactions tab").

    Falls back to original test cases if Gemini is unavailable.

    Args:
        test_cases: List of TestCase objects with basic steps.
        file_changes: List of FileChange objects with code content.
        locators: List of DetectedLocator objects.
        patterns: List of DetectedPattern objects.
        metadata: PRMetadata object.
        change_summary: Human-readable change summary text for context.

    Returns:
        Enhanced list of TestCase objects with detailed steps.
    """
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        logger.info("GEMINI_API_KEY not set — keeping basic test steps")
        return test_cases

    try:
        from google import genai
        client = genai.Client(api_key=api_key)
    except Exception as e:
        logger.warning("Failed to initialize Gemini client: %s", e)
        return test_cases

    # Build a map of file_path -> code content for context
    file_content_map = {}
    for fc in file_changes:
        if fc.head_content:
            # Only include first 200 lines to keep prompt manageable
            lines = fc.head_content.splitlines()[:200]
            file_content_map[fc.path] = "\n".join(lines)

    # Group test cases by source file and enhance in batches
    groups: dict[str, list] = {}
    for tc in test_cases:
        groups.setdefault(tc.source_file, []).append(tc)

    enhanced_cases = []
    for file_path, cases in groups.items():
        code_snippet = file_content_map.get(file_path, "")
        short_name = file_path.rsplit("/", 1)[-1] if "/" in file_path else file_path

        # Build prompt for this batch — include change summary for context
        prompt = _build_enhancement_prompt(cases, code_snippet, short_name, metadata, change_summary)

        try:
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
            )
            enhanced = _parse_enhanced_response(response.text, cases)
            enhanced_cases.extend(enhanced)
            logger.info("Enhanced %d test cases for %s via Gemini", len(cases), short_name)
        except Exception as e:
            logger.warning("Gemini enhancement failed for %s: %s — keeping original steps", short_name, e)
            enhanced_cases.extend(cases)

    return enhanced_cases


def _build_enhancement_prompt(cases: list, code_snippet: str, file_name: str, metadata, change_summary: str = "") -> str:
    """Build a prompt asking Gemini to generate detailed test steps."""

    # Summarize what each test case is about
    tc_summaries = []
    for i, tc in enumerate(cases):
        tc_summaries.append(f"""
Test Case {i+1}:
  ID: {tc.id}
  Title: {tc.title}
  Trigger: {tc.trigger}
  Current Steps: {'; '.join(tc.steps)}
""")

    # Extract "What QA Should Test" and "Screens Affected" from summary for focused context
    summary_context = ""
    if change_summary:
        import re
        # Extract key sections from the change summary
        sections_to_extract = ["What Changed", "Screens Affected", "What QA Should Test", "Risk Areas"]
        for section_name in sections_to_extract:
            pattern = rf"##\s*{re.escape(section_name)}.*?\n(.*?)(?=\n##|\Z)"
            match = re.search(pattern, change_summary, re.DOTALL | re.IGNORECASE)
            if match:
                summary_context += f"\n### {section_name}:\n{match.group(1).strip()}\n"

    prompt = f"""You are a QA automation engineer writing detailed test steps for a mobile app (Android/iOS).

The app is "Bizom" - a field sales force automation app. Users are sales representatives who visit retail outlets.

Given the code context and change summary below, rewrite the test steps to be specific and automation-ready. Each step should describe exactly what action to perform in the app — like "Tap the hamburger menu", "Navigate to Transactions tab", "Scroll to the order card", etc.

**File:** {file_name}
**PR Branch:** {metadata.source_branch}
{f'''
**Change Summary (What was modified and what to test):**
{summary_context}
''' if summary_context else ''}
**Code Context (first 200 lines):**
```kotlin
{code_snippet[:4000]}
```

**Test Cases to Enhance:**
{''.join(tc_summaries)}

---

For each test case, return ONLY a JSON array with this structure:
```json
[
  {{
    "id": "TC1",
    "steps": ["1. Login to Bizom app with valid credentials", "2. Tap hamburger menu (top-left)", "3. ..."],
    "preconditions": ["User has valid login credentials", "App is installed on device"],
    "expected_results": ["The element is visible on screen", "..."]
  }}
]
```

Rules for steps:
- Start with login/launch if needed
- Include specific navigation (which tab, which menu, which button)
- Reference actual UI element names from the code (testTag values, content descriptions)
- Use the change summary to understand WHAT the feature does and WHICH screens to navigate to
- Be specific enough that a test automation tool can execute them (avoid vague steps like "Navigate to the screen with the state variable")
- Keep each step as one atomic action
- Include verification steps (e.g., "Verify the button is displayed")
- NEVER use generic placeholder steps like "Perform the primary interaction" or "Wait for the application to process"

Return ONLY valid JSON, no extra text before or after.
"""
    return prompt


def _parse_enhanced_response(response_text: str, original_cases: list) -> list:
    """Parse Gemini's response and update test cases with enhanced steps."""

    # Try to extract JSON from the response
    text = response_text.strip()

    # Handle markdown code blocks
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0].strip()
    elif "```" in text:
        text = text.split("```")[1].split("```")[0].strip()

    try:
        enhanced_data = json.loads(text)
    except json.JSONDecodeError:
        logger.warning("Failed to parse Gemini response as JSON, keeping original steps")
        return original_cases

    if not isinstance(enhanced_data, list):
        return original_cases

    # Map enhanced data back to test cases
    for i, tc in enumerate(original_cases):
        if i < len(enhanced_data):
            item = enhanced_data[i]
            if isinstance(item, dict):
                if "steps" in item and isinstance(item["steps"], list):
                    tc.steps = item["steps"]
                if "preconditions" in item and isinstance(item["preconditions"], list):
                    tc.preconditions = item["preconditions"]
                if "expected_results" in item and isinstance(item["expected_results"], list):
                    tc.expected_results = item["expected_results"]

    return original_cases
